### Movie Index Action
GET http://localhost:3000/movies.json

### Movie Show Action
GET http://localhost:3000/movies/1.json

### Movie Create Action
POST http://localhost:3000/movies.json
Content-Type: application/json

{
  "title": "Tolkien",
  "year": "2019",
  "plot": "As a young student, J.R.R. Tolkien finds love, friendship and artistic inspiration among a group of fellow outcasts. Their brotherhood soon strengthens as Tolkien weathers the storm of a tumultuous courtship with Edith Bratt and the outbreak of World War I. These early life experiences later inspire the budding author to write the classic fantasy novels The Hobbit and The Lord of the Rings.",
  "director": "Dome Karukoski",
  "english": true
}

### Movie Update Action
PATCH http://localhost:3000/movies/3.json 
Content-Type: application/json

{
   "title": "Tolkien!"
}

### Movie Destroy Action
DELETE http://localhost:3000/movies/1.json

### Actor Index Action
GET http://localhost:3000/actors.json

### Actor Show Action
GET http://localhost:3000/actors/1.json

### Actor Create Action
POST http://localhost:3000/actors.json
Content-Type: application/json

{
  "first_name": "Emilia",
  "last_name": "Clark",
  "known_for": " Daenerys Targaryen in the Game of Thrones series",
  "age": 30,
  "gender": "F"
}

### Actor Update Action
PATCH http://localhost:3000/actors/2.json 
Content-Type: application/json

{
   "known_for": "Daenerys Targaryen: Queen of Meereen, Khaleesi of the Great Grass Sea, Mother of Dragons, The Unburnt, Breaker of Chains in the Game of Thrones series"
}

### Actor Destroy Action
DELETE http://localhost:3000/actors/1.json
